### ISSUE TITLE
GitHub Action workflow to check conda environment

### ISSUE THREAD

**Issue by wigging** [pybamm-team/liionpack#74]
Can someone add a GitHub Action to build and check the conda environment? I don't have permission to update the workflow in this repository but I believe it would be something like this:

```yaml
  build:
    needs: style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
```
